### ISSUE TITLE
How to display `C` code?

### ISSUE THREAD

**Issue by hengxin** [edemaine/reveal-pug-talk#1]
Hi Erik,

I am very impressed with this project.

I am new to the technology you use in `reveal-pug-talk` and I failed to display `C` code in presentation. Could you show me an example, e.g., with the C `hello-world` program?  And any documentation there?

Thanks for your efforts.

Best,
Hengfeng

**Comment by edemaine** [comment]
Something like this should work:

```pug
pre.
  main() {
    printf("Hello, world!");
  }
```

See https://pugjs.org/language/plain-text.html#block-in-a-tag
